spring:
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url:  jdbc:mysql://10.71.178.31:3306/labmanager?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username:  root
    password:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false

mybatis:
    mapperLocations:  classpath:/mapper/**/*.xml
    #或者使用mapper-location
    configLocation: classpath:mybatis-config.xml
    #或者使用 config-locaton
server:
  port: 8080